### ISSUE TITLE
wandb: Enter your choice:

### ISSUE THREAD

**Issue by Liampour** [Anonymous1563/Bayesian-Enhancement-Model#2]
When I am trying to run the training the following command is appearing to terminal

> wandb: Enter your choice:

Any suggestions?

**Comment by BinCVER** [comment]
You may need to register for a Weights & Biases (wandb) account and log in on your device via the command line using `wandb login` .
Alternatively, you can comment out the wandb configuration in the model configuration file (e.g., GC_Net.yaml).

If you found our repository useful, please consider giving it a star. Thank you!

**Comment by Liampour** [comment]
Thank you very much for your help!
After creating an account on Weights & Biases I have successfully logged in and the process started. 
The following error appeared.
` Name Dataset_PairedImage_Mask is not found, use name: Dataset_PairedImage_Mask_basicsr!
Traceback (most recent call last):

  File "C:\Users\UserName\Desktop\Bayesian-Enhancement-Model-main\basicsr\train.py", line 269, in <module>
    train_pipeline(root_path)

  File "C:\Users\UserName\Desktop\Bayesian-Enhancement-Model-main\basicsr\train.py", line 127, in train_pipeline
    result = create_train_val_dataloader(opt, logger)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Desktop\Bayesian-Enhancement-Model-main\basicsr\train.py", line 42, in create_train_val_dataloader
    train_set = build_dataset(dataset_opt)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\basicsr\data\__init__.py", line 34, in build_dataset
    dataset = DATASET_REGISTRY.get(dataset_opt['type'])(dataset_opt)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\basicsr\utils\registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!") `

> KeyError: "No object named 'Dataset_PairedImage_Mask' found in 'dataset' registry!"

**Comment by BinCVER** [comment]
I believe you have the basicsr package installed via pip. Please uninstall it first, then install our version of basicsr by running the following command:
`python setup.py develop --no_cuda_ext`

**Comment by Liampour** [comment]
Yes that was the problem!
Now the algorithm executes some iterations and the process is interrupted by the following error.


Cannot import dcn. Ignore this warning if dcn is not used. Otherwise install BasicSR with compiling dcn.
Can not import selective_scan_cuda_oflex. This affects speed.
Cannot import selective_scan_cuda. This affects speed.

Traceback (most recent call last):
  File "C:\Users\UserName\Desktop\Bayesian-Enhancement-Model-main\basicsr\train.py", line 269, in <module>
    train_pipeline(root_path)

  File "C:\Users\UserName\Desktop\Bayesian-Enhancement-Model-main\basicsr\train.py", line 185, in train_pipeline
    total_grad_norm = model.optimize_parameters(current_iter)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\users\UserName\desktop\bayesian-enhancement-model-main\basicsr\models\condition_generator_model.py", line 182, in optimize_parameters
    _, preds = self.net_g(self.lq, mask=self.mask)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\users\UserName\desktop\bayesian-enhancement-model-main\basicsr\archs\UNet_arch.py", line 471, in forward
    fea = subnet(fea)
    ^^^^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\users\UserName\desktop\bayesian-enhancement-model-main\basicsr\archs\UNet_arch.py", line 351, in forward
    fea = en_block(fea)
          ^^^^^^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\users\UserName\bayesian-enhancement-model-main\basicsr\archs\UNet_arch.py", line 240, in forward
    x = block(x)
        ^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\users\UserName\desktop\bayesian-enhancement-model-main\basicsr\vmamba\models\vmamba.py", line 1377, in forward
    return self._forward(input)
     ^^^^^^^^^^^^^^^^^^^^

  File "c:\users\UserName\desktop\bayesian-enhancement-model-main\basicsr\vmamba\models\vmamba.py", line 1328, in _forwardv01
    x = x + self.drop_path(self.op(self.norm(x)))
    ^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\users\UserName\desktop\bayesian-enhancement-model-main\basicsr\vmamba\models\vmamba.py", line 711, in forwardv2
    y = self.forward_core(x)
    ^^^^^^^^^^^^^^^^^^^^

  File "c:\users\UserName\desktop\bayesian-enhancement-model-main\basicsr\vmamba\models\vmamba.py", line 657, in forward_corev2
    xs = cross_scan_fn(x, in_channel_first=True, out_channel_first=True, scans=_scan_mode, force_torch=scan_force_torch)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\users\UserName\desktop\bayesian-enhancement-model-main\basicsr\vmamba\models\csm_triton.py", line 496, in cross_scan_fn
    return CSF.apply(x, in_channel_first, out_channel_first, one_by_one, scans)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\users\UserName\desktop\bayesian-enhancement-model-main\basicsr\vmamba\models\csm_triton.py", line 418, in forward
    triton_cross_scan_flex[(NH * NW, NC, B)](
  File "C:\Users\UserName\anaconda3\Lib\site-packages\triton\runtime\jit.py", line 160, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\triton\runtime\jit.py", line 341, in run
    device = driver.get_current_device()
             ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\triton\runtime\driver.py", line 22, in __getattr__
    self._initialize_obj()
  File "C:\Users\UserName\anaconda3\Lib\site-packages\triton\runtime\driver.py", line 19, in _initialize_obj
    self._obj = self._init_fn()
                ^^^^^^^^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\triton\runtime\driver.py", line 8, in _create_driver
    return actives[0]()
    ^^^^^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\triton\backends\nvidia\driver.py", line 411, in __init__
    self.utils = CudaUtils()  # TODO: make static
            ^^^^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\triton\backends\nvidia\driver.py", line 55, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\triton\backends\nvidia\driver.py", line 32, in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dir, include_dir, libraries)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\UserName\anaconda3\Lib\site-packages\triton\runtime\build.py", line 52, in _build
    raise RuntimeError("Failed to find C compiler. Please specify via CC environment variable.")

> RuntimeError: Failed to find C compiler. Please specify via CC environment variable.

**Comment by BinCVER** [comment]
Have you installed selective_scan by running `cd kernels/selective_scan && pip install .`?  If not, please try running this command.

**Comment by Liampour** [comment]
I have tried to install it, some packages installed successfully but lots of errors appeared.

The initial part of the errors is as follows

`Requirement already satisfied: einops in c:\users\UserName\anaconda3\lib\site-packages (from selective-scan==0.0.2) (0.8.0)
Requirement already satisfied: filelock in c:\users\UserName\anaconda3\lib\site-packages (from torch->selective-scan==0.0.2) (3.13.1)
Requirement already satisfied: typing-extensions in c:\users\UserName\anaconda3\lib\site-packages (from torch->selective-scan==0.0.2) (4.11.0)
Requirement already satisfied: sympy in c:\users\UserName\anaconda3\lib\site-packages (from torch->selective-scan==0.0.2) (1.12)
Requirement already satisfied: networkx in c:\users\UserName\anaconda3\lib\site-packages (from torch->selective-scan==0.0.2) (3.2.1)
Requirement already satisfied: jinja2 in c:\users\UserName\anaconda3\lib\site-packages (from torch->selective-scan==0.0.2) (3.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\UserName\anaconda3\lib\site-packages (from jinja2->torch->selective-scan==0.0.2) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\users\UserName\anaconda3\lib\site-packages (from sympy->torch->selective-scan==0.0.2) (1.3.0)
Using cached ninja-1.11.1.1-py2.py3-none-win_amd64.whl (312 kB)
Building wheels for collected packages: selective-scan
  Building wheel for selective-scan (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [1482 lines of output]`


The final part of the errors is the following

`Error limit reached.
      100 errors detected in the compilation of "csrc/selective_scan/cusoflex/selective_scan_core_bwd.cu".
      Compilation terminated.
      error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\bin\\nvcc.exe' failed with exit code 4294967295
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for selective-scan
  Running setup.py clean for selective-scan
Failed to build selective-scan
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (selective-scan)`

Should I create a new post and post the entire error??

**Comment by BinCVER** [comment]
Try installing `mamba_ssm` with `pip install mamba_ssm==1.0.1`, though it may be slower. Alternatively, check the [VMamba repo](https://github.com/MzeroMiko/VMamba) for similar issues and possible solutions.

**Comment by Liampour** [comment]
Unfortunately I was not able to solve this issue, its quite hard to install mamba_ssm in Windows and the recemented solutions dont seem to work for me. 
Thank you for your time and effort

**Comment by BinCVER** [comment]
You can deploy the code on WSL; it works well for me.

**Comment by Liampour** [comment]
On WSL all the packages installed successfully!! I'm currently having a problem installing CUDA on WSL and I couldn't try the model but this is out of scope of this repository. I really appreciate your assistance!! Once again, thank you very much for your help and suggestions!

**Comment by russellllaputa** [comment]
You're very welcome!

**Comment by BinCVER** [comment]
You're very welcome!
